### ISSUE TITLE
Allow receiving on encrypted datasets

### ISSUE THREAD

**Issue by leanderseidlitz** [psy0rz/zfs_autobackup#60] opened 2020-12-22 21:01 UTC
Encrypted datasets do not support the embedded_data feature. Still, it is used if the sending side is unencrypted. Receival on an encrypted dataset will fail.

Commenting
```
#        if 'embedded_data' in features and "-e" in self.zfs_node.supported_send_options:
#            cmd.append("-e") # WRITE_EMBEDDED, more compact stream
```
out in `send_pipe` solves the problem for me, I can then receive using
`/root/zfsautobackup/zfs-autobackup.py --ssh-source t440 echo tank/t440 --no-snapshot --clear-refreservation --clear-mountpoint --filter-properties encryption --verbose`
The dataset then inherits the encryption properties from the parent.

Proposal: The choice whether -e is set in the zfs send should also be dependent on whether the receiving side supports it.

I will try to submit a pull request, at the moment I am missing the time to do so though.

**Comment by psy0rz** [comment] 2020-12-23 09:08
The --raw is designed for backupping encrypted datasets.

It isn't tested however, so im not sure if it works. (travis doesnt the zfs version that has encryption yet)

**Comment by leanderseidlitz** [comment] 2020-12-23 10:12
I believe --raw works, if both sides are encrypted. I have a somewhat special setup since the sending side is unencrypted and the receiving side is encrypted.

I believe using --raw will not work in this setup since according to the documentation of --raw: "For unencrypted datasets, this flag will be equivalent to -Lec", therefore enabling embedded_data, which is unsupported by the receiving encrypted side.

Using --raw leads to `cannot receive new filesystem stream: kernel modules must be upgraded to receive this stream.`, for me which in this case is caused by trying to receive a stream with the embedded_data feature while unsupported.

**Comment by psy0rz** [comment] 2020-12-24 12:44
> 
> Proposal: The choice whether -e is set in the zfs send should also be dependent on whether the receiving side supports it.
> 

We now only check if the userspace zfs-tool AND the zpool support it. 

There are currently no provisions built in to check per dataset if it supports this, by checking for encryption or something.

A PR is more than welcome :) 

The lazy way out would be an option like --no-write-embed, to disable it globally.

**Comment by psy0rz** [comment] 2021-02-06 21:43
I switched to github actions and that supports zfs encryption, so I'll add a regression test and a fix for this soon. I think we should be able to automaticly enable the correct options to support backing up encrypted data.

**Comment by psy0rz** [comment] 2021-04-18 22:48
Working on it now. zfs-autobackup will handle special cases like this.

The --raw option wont be needed anymore since its autodetected if its needed.

There will be a --decrypt option to explicitly force decryption for new datasets on the target side.

**Closed** 2021-04-20 21:20 UTC
Labels: bug

**Comment by psy0rz** [comment] 2021-04-20 21:55
Fixed it and added a bunch of cool stuff: https://github.com/psy0rz/zfs_autobackup#how-zfs-autobackup-handles-encryption

Like and star if you like it :)

**Comment by psy0rz** [comment] 2021-04-20 22:16
I've created a release for the python package but the github workflow isnt triggering. Will check again tomorrow.

**Comment by psy0rz** [comment] 2021-04-21 21:58
To get it, just upgrade:

pip install --upgrade --pre zfs-autobackup
