### ISSUE TITLE
Local only, "in place" snapshots

### ISSUE THREAD

**Issue by wxcafe** [psy0rz/zfs_autobackup#46] opened 2020-05-11 20:33 UTC
Would be cool to be able to run without target or source, and have zfs_autobackup do snapshots on the dataset itself. Currently I use a "hack" where I run `zfs_autobackup --ssh-target 127.0.0.1 local none --no-send --keep-source 15min6h` but it'd be nice to be able to just go `zfs_autobackup local --keep 15min6h` or something.

Also, currently this setup doesn't work properly (i.e. zfs_autobackup still connects to the "target" and tells me `none` doesn't exist) :/ (it worked with RC-9)

**Comment by psy0rz** [comment] 2020-05-11 22:15
The problem is that zfs_autobackup needs to know what the common snapshot is, before it can delete anything. Therefore both source and target are needed, for now. (or we need to mark the common snapshot somehow)

Making just a snapshot (without deleting anything) should be possible with some minimal changes to the code.

First i'm focussing on unit-testing to speed up development and prevent regressions when we add new features like these. :)

**Comment by wxcafe** [comment] 2020-05-11 22:27
well, if I'm using `--no-send` and I'm the source, there's no reason to check what the target wants, though.

But yeah I get that this isn't a priority :)

**Comment by psy0rz** [comment] 2020-05-12 10:24
If you only want to take snapshots, you're right: There shouldn't be a reason to specify and connect the target. 

I'll add that feature: if you dont specify a target, it will only take a snapshot. (it will imply a --no-send and it wont run the Thinner.)

**Comment by wxcafe** [comment] 2020-05-12 15:46
This is exactly what I meant yes :) Thanks! Though it should probably be "if you specify neither a target nor a source" :)

**Comment by jason-but** [comment] 2020-06-04 04:55
Yes, can I also add this would be excellent. With this change, zfs-autobackup would be perfect to manage rolling snapshots as well as backups. Having looked at your thinning code, it is the most elegant solution to this problem I have seen and is streets ahead of most other auto-snapshot-purging scripts I've seen

I also support this based on my deployment, my backup disk is a local - USB - external drive so my daily backup script essentially (with error checking and logging) does:
```
zfs import backup_pool
zfs-autobackup <options> backup backup_pool
zfs export backup_pool
```
Then I have an hourly snapshot script which
```
zfs-autobackup --keep-source <rules> --no-send local_snap backup_pool
```
This works fine as long as **backup_pool** is imported, which it is not, now I get errors that the destination pool is not present even though - as above - it is not relevant given the **no-send** option

So my plus+1 to allowing no target

**Comment by lzhang10** [comment] 2020-06-27 00:32
Is there any update on this very useful snapshot-only feature when the target pool is not imported? I usually run zfs-autobackup to backup to a USB external drive. If the drive is not plugged in, I can not perform backup via snapshot at all. It is not offsite backup but is still a useful form of backup when the target pool is offline. Currently I have to run znapzend for that purpose.

**Comment by psy0rz** [comment] 2020-07-07 09:25
Yes this will be added as soon as all regression tests are completed. (and i have enough time)

**Comment by psy0rz** [comment] 2020-07-09 17:50
This is now fixed in master.

You can just not specify target_path and it will work as  normal snapshot tool on source. Offcourse it will keep common snapshots by looking at the holds (so watch out if you use --no-holds as well, then it can actually remove common snapshots)

So in its most basic form you can now just use:

```console
zfs-autobackup somename --verbose
```


Edwin

**Comment by psy0rz** [comment] 2020-07-09 17:51
note: i will update the documentation accordingly.

**Closed** 2020-07-09 17:51 UTC
Labels: enhancement

**Comment by jason-but** [comment] 2020-07-10 03:02
Excellent, just downloaded and ran some tests, works great

Thanks for addressing this feature

**Comment by psy0rz** [comment] 2020-07-10 10:51
I forgot to mention: It will now always FIRST make the snapshot, and in the later steps it will actually do stuff with the target. So if the target doesnt exist or if ssh-target is unreachable, it doesnt matter: It will made the snapshot.

**Comment by psy0rz** [comment] 2020-07-10 11:15
docs https://github.com/psy0rz/zfs_autobackup#use-as-snapshot-tool

**Comment by wxcafe** [comment] 2020-07-10 20:54
That's really cool! thanks a lot!

**Comment by lzhang10** [comment] 2020-07-11 01:18
Can confirm this now works as intended. Thanks for the quick update.
