### ISSUE TITLE
Destroy old snapshots *after* sending the new ones in

### ISSUE THREAD

**Issue by wxcafe** [psy0rz/zfs_autobackup#45] opened 2020-05-11 02:53 UTC
When zfs_autobackup runs, it destroys old snapshots on the source before sending the new snapshots to the target. If for some reason receives fail, after a while the target will not have any snapshots in common with the source (source continues taking new snapshots and destroying old ones, target never gets the new snapshots) and a full send will have to be done.

old snapshots should be deleted only once new ones have been received on the target *and it has been verified that they have been received correctly (i.e. the latest snapshot on the target is the same as on the source)*

**Comment by psy0rz** [comment] 2020-05-11 10:12
This is obviously one of the main things that shouldn't happen.We even use holds to prevent the administrator or other tools from accidently deleting common snapshots.

This was a bug due a regression in a recent release candidate.

Its fixed in RC10, please try it.

**Closed by psy0rz** 2020-05-11 10:12 UTC

**Comment by wxcafe** [comment] 2020-05-12 01:34
updated to RC10, and I seem to still have this problem:

```
  zfs-autobackup v3.0-rc10 - Copyright 2020 E.H.Eefting (edwin@datux.nl)

[...]

  #### Sending and thinning
  [Source] rpool/ROOT/debian@support-20200511153202: Destroying
  [Target] rpool/backups/imaginaires/rpool/ROOT/debian@support-20200511013201: Destroying
  [Target] rpool/backups/imaginaires/rpool/ROOT/debian@support-20200512013201: receiving incremental
```

**Comment by psy0rz** [comment] 2020-05-12 10:21
Snapshots that are not needed anymore are deleted as soon as possible, to prevent any space issues.

So it will indeed destroy stuff before it starts sending, but only stuff thats not needed anymore. 

This is also the partly the reason that we cant delete snapshots without connecting the target ( #46 ). Zfs-autobackup needs to check to see which snapshots still need to be transferred, before it can decide what to delete.

If you do get an error with the above command, please post the complete output. 

Good luck. :)

**Comment by wxcafe** [comment] 2020-05-12 15:55
Well, I understand that there is a space concern, but on the other hand I feel like recovering gracefully from `receive` errors would be good too? Currently if receive fails a few times I can end up with no common snapshots on both side, and I'd need to re-do a full transfer

**Comment by psy0rz** [comment] 2020-05-12 16:06
That shouldn't happen anymore since rc10. If it does, please post the full output (via a gist if its too big).

It should never lose the common snapshot, no matter how many times it fails. If it does, its a bug.

**Comment by wxcafe** [comment] 2020-05-12 16:13
ah, sorry, it never happened to me it was just an observation from the logging. I just looked at the code and it's totally fine indeed, thanks to the `find_common_snapshot()` thing.

Sorry for that!

**Comment by psy0rz** [comment] 2020-05-12 16:16
no problem. things are indeed getting quite complex, so i decide to start wrting unittests to test everyting, before adding new features. :)
